version: '3.9'
services:
  web: #service_name = web
    build: . # build tu Dockerfile = .
    command: python3 manage.py runserver 0.0.0.0:8000 #=container=8000
    volumes:
      - .:/code #backup voi host
    ports:
      - "8000:8000"

## browser<localhost=8000>:container=8000